### PR TITLE
Improves .resetButton alignment with link

### PR DESCRIPTION
**Pull request by sfrieson-cbi**
## Description
Improves the alignment of `<button type="resetButton>` with surrounding text . Here is [a sandbox](https://codesandbox.io/s/unruffled-joliot-gmwnm) to play with the changes. The screenshot below shows the issue blown up, but it's more noticeable in the real situation where the font is smaller.

## Screenshots
image

## Checklist
- [x] Docs have been rebuilt (`yarn build:full`)
- [x] All unit tests pass
- [ ] Snapshots have been updated
- [x] No lint errors or warnings have been introduced
- [ ] **[Version bumped](https://github.com/cbinsights/form-design-system#updating-version-number) if appropriate**

### CODE REVIEW

**Comment by sfrieson-cbi** [comment]
Were you thinking something like this @rey-wright?

**Comment by rey-wright** [comment]
Up to you!

Screen Shot 2020-05-05 at 4 16 15 PM

I was personally thinking something like your image here. Basically I just want to be able to quickly come in and see things are still aligned as I adjust different css.

**Comment by sfrieson-cbi** [comment]
Yeah, I didn't add a link because links should already be aligned with the surrounding inline content. Also, someone's UI design may not necessariy be comparing a button to a link.

**Comment by rey-wright** [comment]
makes sense. Cool I think this is good to go, thanks for adding that story.

**Comment by rey-wright** [comment]
I'll actually merge this one myself as there's some other PR's I want to merge and it'll introduce conflicts on yours.

**Pull request merged**
