### PR TITLE
125/base styles/uip 194 form defaults

### PR DESCRIPTION
**Pull request by akdetrick**
## Description
Add default styles for input elements.

**Breaking changes** (merging to `release/6.0`)
A full list of changes required are in this ticket: https://cbinsights.atlassian.net/browse/UIP-487

## Screenshots
Screen Shot 2019-11-19 at 12 18 48 PM
Screen Shot 2019-11-19 at 12 18 59 PM

## Checklist
- [x] Docs have been rebuilt (`yarn build:full`)
- [x] All unit tests pass
- [x] Snapshots have been updated
- [x] No lint errors or warnings have been introduced
- [x] **[Version bumped](https://github.com/cbinsights/form-design-system#updating-version-number) if appropriate**

### CODE REVIEW

**Comment by rey-wright** [comment]
Screen Shot 2019-11-19 at 3 29 53 PM

This is what I see in Safari on the input error in fds-styles

**Comment by rey-wright** [comment]
Screen Shot 2019-11-19 at 3 30 37 PM

Same thing for the reset

**Comment by rey-wright** [comment]
this specific thing isn't a new issue introduced with your changes, but the reset button in safari when clicked, disappears...

**Comment by rey-wright** [comment]
Screen Shot 2019-11-19 at 3 35 55 PM

This input is a bit taller in safari

**Comment by rey-wright** [comment]
Screen Shot 2019-11-19 at 3 35 14 PM

I haven't even looked at the code yet, but it seems like this error border appears when a valid url is in the input. It won't error if I put a full url though: http://www.blah.com

**Comment by rey-wright** [comment]
I could be wrong, but it seems like we're not linking to this new form specimen document in the base docs file (same place where we're linking to the typography specimen document)

**Comment by rey-wright** [comment]
Code looks good!

**Comment by akdetrick** [comment]
Made some changes based on above feedback:

- Fixed the Safari/Firefox issue. 
- Added form specimen link to docs

**Pull request merged**
