### PR TITLE
Checkbox fixes

### PR DESCRIPTION
**Pull request by David-Cohen35**

### CODE REVIEW

**Review by reywright — APPROVED** [review]
LGTM!

**Comment by David-Cohen35** [comment]
this breaks tests in cbi-site - need to work on those before merging

**Comment by reywright** [comment]
@David-Cohen35 nice work on checking that before merging 🎉

**Comment by David-Cohen35** [comment]
> 

yeah doing my best to break fewer things lol

**Review by ivanhdez28 — APPROVED** [review]
looks good

**Pull request closed without merging**
