### PR TITLE
124/v5/uip 305 limit icon interface

### PR DESCRIPTION
**Pull request by akdetrick**
## Description
- clean up extraneous `IconComponent` template
- remove usage of `className` prop and validation in icon component wrapper
- update prop interface docs

## Screenshots
Screen Shot 2019-10-11 at 3 26 11 PM

## Checklist
- [x] Docs have been rebuilt (`yarn build:full`)
- [x] All unit tests pass
- [x] Snapshots have been updated
- [x] No lint errors or warnings have been introduced
- [x] **[Version bumped](https://github.com/cbinsights/form-design-system#updating-version-number) if appropriate**

### CODE REVIEW

**Comment by reywright** [comment]
I'm trying to figure out a magic regex that will show all `Icon` components with the className prop, to know how much work we have to do here, to inform whether this should go in v5 or not.

**Comment by akdetrick** [comment]
Given that the prop interface for icon components change, this will have be released as a "breaking change" regardless.

I found 36 instances of `className` being used on icon components in `cbi-site`.

```
                  <CropIcon className={styles['crop-button-icon']} size="xs" color="slate" />
        <DenyIcon className={cx(styles['remove-icon'])} size="xs" color={FDS.FONT_COLOR_PRIMARY} />
              <AscendingIcon className="valign--center" size="xs" />
              <DescendingIcon className="valign--center" size="xs" />
              icon={<ApproveIcon className="valign--center" size="xs" />}
            icon={<TrashIcon className="valign--center" size="xs" />}
            <DenyIcon className={styles.icon20} size="s" color="white" />
          <AddIcon size="xs" color={color} /><span className={styles.add}>Add</span>
        <SearchIcon size="xs" className={styles.rowTextInputIcon} />
              <UpdateIcon size="xs" className={styles.retryIcon} /> Retry
      action={<StatusIcon className={status === READY ? styles.hoverRowAction : undefined} status={status} />}
              <UpdateIcon size="xs" className={styles.retryIcon} /> Retry
          action={<StatusIcon status={status} className={status === 'ready' ? commonStyles.hoverRowAction : ''} />}
        <AddIcon className={props.classes.add} />
    <ResetIcon size="xs" className={styles['reset-icon']} /> Reset all Filters
            ><div className={styles.insertRowIconWrapper}><ApproveIcon color="white" size="xs" /></div></button>
              <VisualizeIcon className={styles['add-icon']} size="xs" />
              <NopeIcon className={styles['add-icon']} size="xs" />
          <TrashIcon className={styles['add-icon']} size="xs" />
          <ApproveIcon className={styles['add-icon']} size="xs" />
      icon: <SheetIcon size="xs" className="padding--right--half" />,
            iconComponent={<CloneIcon className={styles.icon} />}
            iconComponent={<ShareIcon className={styles.icon} />}
            iconComponent={<TrashIcon className={styles.icon} />}
                iconComponent={<MoreIcon className={styles.icon} />}
 *    iconComponent={<TrashIcon className={styles.icon} />}
              <ApproveIcon size="xs" className={styles['new-sheet-icon']} />
        <ApproveIcon size="xs" className="margin--right--half" />
                          <TableIcon size="xs" className="margin--right--half" />
            <HomeIcon size="xs" className="margin--right--half" />
            <DenyIcon className={styles.icon} color="white" size="xs" />
    <FilterIcon size="xs" className="color--slate" />
        <ResetIcon size="xs" className={`${styles.icon} valign--center`} />
                    {hashtag.isExpert ? <ExpertTagIcon size="xs" className={styles.icon} /> : <HashtagIcon size="xs" className={styles.icon} />}
                  <SortIcon className={styles['sort-button']} size="xs" />
              <SearchIcon size="xs" className={styles['search-icon']} />
```

(`ack \<[A-Z][a-z]+Icon src/client/ --ignore-dir=src/client/.buildcache --no-filename | grep -v Mui | grep className`)

**Comment by reywright** [comment]
36 is not that bad.

**Comment by reywright** [comment]
@akdetrick what black magic is this regex????

**Comment by akdetrick** [comment]
regarding regex:

`ack` is a drop in replacement for `grep` which gets matching files _and_ searches those files in one pass. The first argument is always treated as a regex pattern.

```
 \<[A-Z][a-z]+Icon src/client/

\<      # escape the <
[A-Z]   # first char will aways be uppercase because ReactCase
[a-z]+  # any number of lowercase chars
Icon    # "Icon"
```

`grep -v Mui` gives us all lines _except_ lines containing "Mui"

`grep className` gives us any lines containing a "className"

**Pull request merged**
