### PR TITLE
UIP-761: classcat

### PR DESCRIPTION
**Pull request by reywright**
## Description
Classcat is up to 2.5x faster, smaller and the api is "basically" the same. There's almost no reason not to use it!

Note: I "did not" change the code for these files manually (other than one hbs file). I created a codeshift transform and it did all the work 🎉 

## Screenshots
n/a

## Checklist
- [x] Docs have been rebuilt (`yarn build:full`)
- [x] All unit tests pass
- [x] Snapshots have been updated
- [x] No lint errors or warnings have been introduced
- [x] **[Version bumped](https://github.com/cbinsights/form-design-system#updating-version-number) if appropriate**

### CODE REVIEW

**Comment by reywright** [comment]
Note: the classcat function signature requires the object to be the first argument. Because of that, the order of the classes changes, hence why all of the snapshots had to be updated.

**Comment by akdetrick** [comment]
@rey-wright Is the idea to wait for v9 before merging? Did the reorganization to a git move on these files, or will you have to re-run codeshift on this?

**Comment by reywright** [comment]
yeah there's no rush, I'll just have to re-run codeshift which is easy peasy

**Comment by akdetrick** [comment]
labelling as don't merge until v9 merges

**Comment by rey-wright** [comment]
Closing in favor of https://github.com/cbinsights/form-design-system/pull/401

**Pull request closed without merging**
